server:
  port: 8102
spring:
  application:
    name: psychology-content-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psychology_site?serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.psychology.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
